IBM/ibm-management-ingress-operator

- pkg/controller/managementingress/handler/configmap.go
- pkg/controller/managementingress/handler/deployment.go
- pkg/controller/managementingress/handler/ingressrequest.go
- pkg/controller/managementingress/managementingress_controller.go
Forget to return err in failed case.
Also updated deployment and configmap log to make it more clear.
> Operator reconcile was not triggered if there is feailure

- deploy/crds/operator.ibm.com_v1alpha1_managementingress_cr.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/0.0.1/ibm-management-ingress-operator.v0.0.1.clusterserviceversion.yaml
- pkg/controller/managementingress/handler/default.go
- pkg/controller/managementingress/handler/deployment.go
- pkg/controller/managementingress/handler/service.go
Also update container listening port to 433 for catalog UI
redirect issue.
> Add default resource limit for operand pod

- deploy/olm-catalog/ibm-management-ingress-operator/1.1.0/ibm-management-ingress-operator.v1.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
- pkg/controller/managementingress/handler/default.go
> update memory limit

- deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Signed-off-by: Yu Wei <yuweiw@cn.ibm.com>
> Remove extra braces for OperandBindInfo.

- deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/controller/managementingress/handler/constants.go
Update common service productVersion from 3.3.0 to 3.4.0
> update cs version

- go.mod
- pkg/controller/managementingress/handler/configmap.go
- pkg/controller/managementingress/handler/constants.go
- pkg/controller/managementingress/handler/ingressrequest.go
Signed-off-by: Wei Yu (Jared) <yuweiw@.cn.ibm.com>
> Added api server info in configmap ibmcloud-cluster-info.

- pkg/controller/managementingress/handler/configmap.go
Signed-off-by: Wei Yu (Jared) <yuweiw@.cn.ibm.com>
> Added ownerReference for configmap ibmcloud-cluster-info when patching.

- common/scripts/multiarch_image.sh
- deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
Use latest image to deploy operator during development script.
> push latest image

- deploy/olm-catalog/ibm-management-ingress-operator/1.2.0/ibm-management-ingress-operator.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
Also changed the image reference from tag to sha digest. Prepared
for 2020 2Q offical release.
> Create beta channel for Common Service 2020 2Q release

- Makefile
- deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/ibm-management-ingress-operator.v1.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.2.1/operator.ibm.com_managementingresses_crd.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
- pkg/controller/managementingress/handler/cert.go
- pkg/controller/managementingress/handler/configmap.go
- version/version.go
There are several commits which are in release-1.2.0 branch, but not in master branch. So rebase master from release-1.2.0.
> Rebase from release-1.2.0 branch

- deploy/crds/operator.ibm.com_managementingresses_crd.yaml
- deploy/crds/operator.ibm.com_v1alpha1_managementingress_cr.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/ibm-management-ingress-operator.v1.3.0.clusterserviceversion.yaml
- pkg/apis/operator/v1alpha1/managementingress_types.go
- pkg/controller/managementingress/handler/deployment.go
- pkg/utils/utils.go
Support creating replicas for management ingress pods.
> support creating replicas for management ingress pods

- pkg/controller/managementingress/handler/deployment.go
Set management ingress replica default value is 1.
> set management ingress replica default value

- deploy/crds/operator.ibm.com_managementingresses_crd.yaml
- deploy/crds/operator.ibm.com_v1alpha1_managementingress_cr.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/ibm-management-ingress-operator.v1.3.0.clusterserviceversion.yaml
- pkg/apis/operator/v1alpha1/managementingress_types.go
- pkg/controller/managementingress/handler/deployment.go
Rename ReplicaCount to Replicas.
> rename ReplicaCount to Replicas

- Makefile
- common/scripts/config_docker.sh
Update CICD pipeline to push image to artifactory repo.
> change cicd pipeline

- common/scripts/multiarch_image.sh
Update multiarch image version.
> update multiarch image version

- deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/ibm-management-ingress-operator.v1.3.0.clusterserviceversion.yaml
- deploy/operator.yaml
This reverts commit b538234e705fd3743bb4f6264c386b52c6399d39.
> Revert "Update csv to use latest operand image"

- deploy/olm-catalog/ibm-management-ingress-operator/1.3.0/ibm-management-ingress-operator.v1.3.0.clusterserviceversion.yaml
- deploy/operator.yaml
Update icp-management-ingress operand image digest.
> update operand image digest

- Makefile
- deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/operator.ibm.com_managementingresses_crd.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
- version/version.go
Create new csv version 1.3.1 for development.
> create new csv version 1.3.1

- deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
Add labels to support power and s390x.
> Add labels to support power and s390x

- build/Dockerfile
- build/Dockerfile.ppc64le
> upate base image

- deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
> change dev channel version

- build/Dockerfile.ppc64le
Update base image to pass va scan.
> update base image

- deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
> remove duplicated field

- deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
> remove-duplicated-field

- deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/controller/managementingress/handler/constants.go
- pkg/controller/managementingress/handler/ingressrequest.go
Remove metering product version.
> remove metering product version

- build/Dockerfile
> upadte base image

- deploy/olm-catalog/ibm-management-ingress-operator/1.3.1/ibm-management-ingress-operator.v1.3.1.clusterserviceversion.yaml
- deploy/operator.yaml
> update image digest

- deploy/olm-catalog/ibm-management-ingress-operator/1.3.3/ibm-management-ingress-operator.v1.3.3.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.3.3/operator.ibm.com_managementingresses_crd.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
- pkg/controller/managementingress/handler/configmap.go
- pkg/controller/managementingress/handler/reconciler.go
- pkg/controller/managementingress/handler/route.go
- pkg/controller/managementingress/managementingress_controller.go
- version/version.go
When operator managed resource was removed accidentally operator will
get the delete event and recreate the missed resource.
> Watch managed resources

- utils/utils.go
If it's cert manager case need to ignore the label from current
deployment spec. Because cert manager use that label to restart
pod when certificate was renewed.
> Still need to compare labels to get deployment update

- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.4.2/ibm-management-ingress-operator.v1.4.2.clusterserviceversion.yaml
Still testing
/do-not-merge
/hold
> update operand imae digest.

- deploy/olm-catalog/ibm-management-ingress-operator/ibm-management-ingress-operator.package.yaml
This PR is only for triggering the prow CI build.
> update the package file to trigger prow build

- OWNERS
> add rcsherro as owner

- build/Dockerfile
- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.4.4/ibm-management-ingress-operator.v1.4.4.clusterserviceversion.yaml
> update UBI image and operand SHA

- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_managementingresses.yaml
- config/crd/bases/operator.ibm.com_managementingresses.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.7.0/ibm-management-ingress-operator.v1.7.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-management-ingress-operator/1.7.0/operator.ibm.com_managementingresses_crd.yaml
v1beta1 -> v1
add minkubeversion
> v1beta1 -> v1

- build/Dockerfile
- common/scripts/config_docker.sh
Changes for : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/48690
> Opt-in for ubi base image automated builds. 

- build/Dockerfile
- common/scripts/config_docker.sh
Reverts IBM/ibm-management-ingress-operator#204 until the problem is resolved.
> Revert "Opt-in for ubi base image automated builds. "

- Makefile
- build/Dockerfile
- common/scripts/config_docker.sh
> Opt-in for ubi base image automated builds

- common/scripts/multiarch_image.sh
- controllers/handler/common.go
- controllers/handler/configmap.go
- controllers/handler/constants.go
- controllers/handler/deployment.go
- controllers/handler/reconciler.go
- controllers/managementingress_controller.go
- main.go
Gather functionality from project-k into cd stream
> Add k functionality

- Makefile
- common/scripts/codecov.sh
> Delete codecov.io reference

- go.mod
- go.sum
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51317
> bump crypto version twistlock cd

- controllers/handler/deployment.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51485
> Get cluster domain from kubernetes default svc on cncf

- README.md
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52251
> trigger prow build with go v1.17.7

- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
IBMPrivateCloud/roadmap/issues/53262
> update image refs to be icr.io

- controllers/handler/route.go
Signed-off-by: Jakub Solecki <Jakub.Solecki@ibm.com>
> increase cp-conosle route timeout to 90s

- README.md
- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- common/scripts/multiarch_image.sh
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
- version/version.go
> version bump for cs3.19.4 to 1.16.4

- common/scripts/multiarch_image.sh
> take multiarch version from version file

- README.md
- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
- version/version.go
> version bump for cs 3.19.5 to 1.16.5

- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
> hide operator in ocp console

- controllers/handler/deployment.go
> resolve panic in deployment when no port is in ibm-cpp-config

- README.md
- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
- version/version.go
> bump version to 1.19.0 for cs 3.22

- Makefile
> update to force rebuild for new go version

- README.md
- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
- version/version.go
> version bump to 1.16.6/CS 3.19.6

- README.md
- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
- version/version.go
> version bump 1.20.0/3.22.0

- Makefile
> force rebuild

- README.md
- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
- version/version.go
> vbump 3.19.8/1.16.8

- Makefile
- build/Dockerfile
- common/scripts/config_docker.sh
- common/scripts/push-images-rh.sh
- config/manager/kustomization.yaml
> update artifactory locations

- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
- version/version.go
> v4.0.0 future version bump

- bundle/manifests/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-management-ingress-operator.clusterserviceversion.yaml
- config/samples/operator_v1alpha1_managementingress.yaml
- version/version.go
> version bump 3.23.1/1.20.1
